[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
via_ir = true
optimizer = true
optimizer_runs = 10000
fs_permissions = [{ access = "read-write", path = "./script/config" }]
evm_version = "paris"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
